NBodies   : 8     #number of bodies to simulate
G   : 1            #np.float32(6.67430e-11) Gravitational Costant
dt  : 0.1         #timestep
SimTime   : 10000     #total simulation time
UseJit    : True 
SaveRes   : True
SaveFolder : '../results/TEST/'