NBodies   : 8     #number of bodies to simulate
G   : 1            #np.float32(6.67430e-11) Gravitational Costant
dt  : 1         #timestep
SimTime   : 1000000     #total simulation time
UseJit    : True 
SaveRes   : True